spring.h2.console:
 enabled: true
 path: /h2

spring.jpa:
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  url: jdbc:h2:mem:jokes
  username: sa
  password:
  driver-class-name: org.h2.Driver


